name: Java CI with Maven
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: adopt
          
      - name: Determine next Tag
        id: DetermineNextTag
        uses: anothrNick/github-tag-action@1.38.0
        env:
          GITHUB_TOKEN: '${{ secrets.VERSIONING }}'
          DRY_RUN: true
      - run: echo next_tag=${{ steps.DetermineNextTag.outputs.new_tag }}

      - name: update version
        run: |
          mvn versions:set -DnewVersion=${{ steps.DetermineNextTag.outputs.new_tag }}
          mvn --batch-mode --update-snapshots package
          
      - name: publish
        run:  mvn --batch-mode deploy -Dversion=${{ steps.DetermineNextTag.outputs.new_tag }}
        env:
          GITHUB_TOKEN: '${{ secrets.VERSIONING }}'
          
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v4
        env:
         GITHUB_TOKEN: ${{ secrets.VERSIONING }}
        with:
         title: ${{ steps.DetermineTag.outputs.new_tag }}
