name: Java CI with Maven
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Determine Tag
        id: DetermineTag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: '${{ github.token }}'
          DRY_RUN: true
      - run: 'echo "next_tag=${{steps.DetermineNextTag.outputs.new_tag}}"'
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: temurin
      - name: update and build
        run: >
          mvn -B -Drevision=${{ steps.DetermineNextTag.outputs.new_tag }} --update-snapshots clean deploy
        env:
          GITHUB_TOKEN: '${{ github.token }}'
          
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v4
        env:
         GITHUB_TOKEN: ${{ github.token }}
        with:
         title: ${{ steps.DetermineTag.outputs.new_tag }}
